<link rel="stylesheet" href="styl.css">
<h1>Registrace</h1>
<form method="post">
    <div>
        <label for="login">Uživatelské jméno:</label>
        <input type="text" name="login" required>
    </div>
   
    <div>
        <label for="heslo">Heslo:</label>
        <input type="password" name="heslo" required>
    </div>
    
    <div>
        <label for="znovu_heslo">Znovu heslo:</label>
        <input type="password" name="znovu_heslo" required>
    </div>
    
    <?php if (!empty($errorMessage)) { ?>
        <div class="error-message"><?php echo $errorMessage; ?></div>
    <?php } ?>
    
    <div>
        <input type="submit" value="Registrovat se">
    </div>
</form>     
    
<p>Už máte účet? Přihlaste se <a href="index.php">zde</a>.</p>
